spring:
  profiles:
    active: test

mybatis:
  type-aliases-package: com.boot.security.server.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true